import { AchievementDefinition } from "./registry";

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // ストリーク系
  {
    id: "streak_3",
    name: "3日連続",
    description: "3日連続でデイリー目標を達成",
    icon: "🔥",
    category: "streak",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.currentStreak >= 3,
  },
  {
    id: "streak_7",
    name: "一週間の習慣",
    description: "7日連続でデイリー目標を達成",
    icon: "🔥",
    category: "streak",
    tier: "silver",
    checkCondition: async (ctx) => ctx.currentStreak >= 7,
  },
  {
    id: "streak_14",
    name: "2週間の継続",
    description: "14日連続でデイリー目標を達成",
    icon: "🔥",
    category: "streak",
    tier: "silver",
    checkCondition: async (ctx) => ctx.currentStreak >= 14,
  },
  {
    id: "streak_30",
    name: "30日の炎",
    description: "30日連続でデイリー目標を達成",
    icon: "🌟",
    category: "streak",
    tier: "gold",
    checkCondition: async (ctx) => ctx.currentStreak >= 30,
  },
  {
    id: "streak_100",
    name: "100日の証明",
    description: "100日連続でデイリー目標を達成",
    icon: "💎",
    category: "streak",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.currentStreak >= 100,
  },
  {
    id: "streak_365",
    name: "1年の伝説",
    description: "365日連続でデイリー目標を達成",
    icon: "👑",
    category: "streak",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.currentStreak >= 365,
  },

  // 累計時間系
  {
    id: "total_hours_10",
    name: "10時間突破",
    description: "累計10時間の活動記録",
    icon: "⏱️",
    category: "total_time",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalHours >= 10,
  },
  {
    id: "total_hours_50",
    name: "50時間達成",
    description: "累計50時間の活動記録",
    icon: "⏱️",
    category: "total_time",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalHours >= 50,
  },
  {
    id: "total_hours_100",
    name: "100時間の軌跡",
    description: "累計100時間の活動記録",
    icon: "⏰",
    category: "total_time",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalHours >= 100,
  },
  {
    id: "total_hours_500",
    name: "500時間の探求",
    description: "累計500時間の活動記録",
    icon: "⏰",
    category: "total_time",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalHours >= 500,
  },
  {
    id: "total_hours_1000",
    name: "1000時間の壁",
    description: "累計1000時間の活動記録",
    icon: "🏆",
    category: "total_time",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalHours >= 1000,
  },
  {
    id: "total_hours_5000",
    name: "5000時間の達人",
    description: "累計5000時間の活動記録",
    icon: "💎",
    category: "total_time",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.totalHours >= 5000,
  },
  {
    id: "total_hours_10000",
    name: "10000時間の伝説",
    description: "累計10000時間の活動記録",
    icon: "👑",
    category: "total_time",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.totalHours >= 10000,
  },

  // 記録数系
  {
    id: "records_1",
    name: "最初の一歩",
    description: "初めての記録を追加",
    icon: "📝",
    category: "records",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 1,
  },
  {
    id: "records_50",
    name: "50件記録",
    description: "50件の活動記録を追加",
    icon: "📝",
    category: "records",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 50,
  },
  {
    id: "records_100",
    name: "100件突破",
    description: "100件の活動記録を追加",
    icon: "📊",
    category: "records",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalRecords >= 100,
  },
  {
    id: "records_500",
    name: "500件の記録者",
    description: "500件の活動記録を追加",
    icon: "📊",
    category: "records",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalRecords >= 500,
  },
  {
    id: "records_1000",
    name: "1000件の達人",
    description: "1000件の活動記録を追加",
    icon: "🏆",
    category: "records",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalRecords >= 1000,
  },
  {
    id: "daily_max_8h",
    name: "フルデイ",
    description: "1日8時間以上の活動記録",
    icon: "💪",
    category: "records",
    tier: "silver",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 8,
  },
  {
    id: "daily_max_12h",
    name: "超集中",
    description: "1日12時間以上の活動記録",
    icon: "🔥",
    category: "records",
    tier: "gold",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 12,
  },

  // 目標達成系
  {
    id: "goal_first_daily",
    name: "初デイリー達成",
    description: "初めてデイリー目標を達成",
    icon: "🎯",
    category: "goals",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.dailyGoalsAchievedDays >= 1,
  },
  {
    id: "goal_first_period",
    name: "初期間達成",
    description: "初めて期間目標を達成",
    icon: "🎯",
    category: "goals",
    tier: "silver",
    checkCondition: async (ctx) => ctx.periodGoalsCompleted >= 1,
  },
  {
    id: "period_goals_3",
    name: "目標コレクター",
    description: "3個の期間目標を達成",
    icon: "🏅",
    category: "goals",
    tier: "silver",
    checkCondition: async (ctx) => ctx.periodGoalsCompleted >= 3,
  },
  {
    id: "period_goals_10",
    name: "目標マスター",
    description: "10個の期間目標を達成",
    icon: "🏆",
    category: "goals",
    tier: "gold",
    checkCondition: async (ctx) => ctx.periodGoalsCompleted >= 10,
  },
  {
    id: "perfect_week",
    name: "完璧な一週間",
    description: "1週間全日100%達成",
    icon: "⭐",
    category: "goals",
    tier: "gold",
    checkCondition: async (ctx) => ctx.currentStreak >= 7,
  },
  {
    id: "perfect_month",
    name: "完璧な一ヶ月",
    description: "1ヶ月100%達成",
    icon: "🌟",
    category: "goals",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.currentStreak >= 30,
  },

  // WhatPulse系
  {
    id: "keys_10k",
    name: "1万キー",
    description: "1日に1万回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 10000,
  },
  {
    id: "keys_50k",
    name: "5万キー",
    description: "1日に5万回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 50000,
  },
  {
    id: "keys_100k",
    name: "10万キー",
    description: "1日に10万回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 100000,
  },
  {
    id: "keys_total_1m",
    name: "累計100万キー",
    description: "累計100万回のキーストローク",
    icon: "💻",
    category: "whatpulse",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 1000000,
  },
  {
    id: "keys_total_10m",
    name: "累計1000万キー",
    description: "累計1000万回のキーストローク",
    icon: "🖥️",
    category: "whatpulse",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 10000000,
  },

  // 特殊系
  {
    id: "early_bird",
    name: "早起き鳥",
    description: "朝6時前に活動開始",
    icon: "🌅",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 1,
  },
  {
    id: "night_owl",
    name: "夜型人間",
    description: "深夜0時以降に活動終了",
    icon: "🦉",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 1,
  },
  {
    id: "multi_category_day",
    name: "マルチタスカー",
    description: "1日に3カテゴリー以上記録",
    icon: "🎨",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.categories >= 3,
  },
  {
    id: "weekend_warrior",
    name: "週末戦士",
    description: "土日に8時間以上の活動",
    icon: "⚔️",
    category: "special",
    tier: "silver",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 8,
  },
  {
    id: "longest_session_4h",
    name: "4時間集中",
    description: "4時間以上の連続記録",
    icon: "🎯",
    category: "special",
    tier: "silver",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 4,
  },
  {
    id: "categories_5",
    name: "バラエティスター",
    description: "5カテゴリー以上を作成",
    icon: "🌈",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.categories >= 5,
  },
  {
    id: "consecutive_record_30",
    name: "30日連続記録",
    description: "30日間連続で記録を追加",
    icon: "📅",
    category: "special",
    tier: "gold",
    checkCondition: async (ctx) => ctx.consecutiveDaysRecorded >= 30,
  },
  {
    id: "consecutive_record_100",
    name: "100日連続記録",
    description: "100日間連続で記録を追加",
    icon: "📅",
    category: "special",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.consecutiveDaysRecorded >= 100,
  },
];
