import { AchievementDefinition } from "./registry";

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // ===== ストリーク系 =====
  {
    id: "streak_3",
    name: "3日連続",
    description: "3日連続でデイリー目標を達成",
    icon: "🔥",
    category: "streak",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.currentStreak >= 3,
  },
  {
    id: "streak_7",
    name: "一週間の習慣",
    description: "7日連続でデイリー目標を達成",
    icon: "🔥",
    category: "streak",
    tier: "silver",
    checkCondition: async (ctx) => ctx.currentStreak >= 7,
  },
  {
    id: "streak_14",
    name: "2週間の継続",
    description: "14日連続でデイリー目標を達成",
    icon: "🔥",
    category: "streak",
    tier: "silver",
    checkCondition: async (ctx) => ctx.currentStreak >= 14,
  },
  {
    id: "streak_21",
    name: "3週間の継続",
    description: "21日連続でデイリー目標を達成",
    icon: "🔥",
    category: "streak",
    tier: "silver",
    checkCondition: async (ctx) => ctx.currentStreak >= 21,
  },
  {
    id: "streak_30",
    name: "30日の炎",
    description: "30日連続でデイリー目標を達成",
    icon: "🌟",
    category: "streak",
    tier: "gold",
    checkCondition: async (ctx) => ctx.currentStreak >= 30,
  },
  {
    id: "streak_50",
    name: "50日の執念",
    description: "50日連続でデイリー目標を達成",
    icon: "💫",
    category: "streak",
    tier: "gold",
    checkCondition: async (ctx) => ctx.currentStreak >= 50,
  },
  {
    id: "streak_100",
    name: "100日の証明",
    description: "100日連続でデイリー目標を達成",
    icon: "💎",
    category: "streak",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.currentStreak >= 100,
  },
  {
    id: "streak_200",
    name: "200日の鉄人",
    description: "200日連続でデイリー目標を達成",
    icon: "🦾",
    category: "streak",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.currentStreak >= 200,
  },
  {
    id: "streak_365",
    name: "1年の伝説",
    description: "365日連続でデイリー目標を達成",
    icon: "👑",
    category: "streak",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.currentStreak >= 365,
  },

  // ===== 累計時間系 =====
  {
    id: "total_hours_10",
    name: "10時間突破",
    description: "累計10時間の活動記録",
    icon: "⏱️",
    category: "total_time",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalHours >= 10,
  },
  {
    id: "total_hours_25",
    name: "25時間突破",
    description: "累計25時間の活動記録",
    icon: "⏱️",
    category: "total_time",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalHours >= 25,
  },
  {
    id: "total_hours_50",
    name: "50時間達成",
    description: "累計50時間の活動記録",
    icon: "⏱️",
    category: "total_time",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalHours >= 50,
  },
  {
    id: "total_hours_100",
    name: "100時間の軌跡",
    description: "累計100時間の活動記録",
    icon: "⏰",
    category: "total_time",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalHours >= 100,
  },
  {
    id: "total_hours_200",
    name: "200時間の蓄積",
    description: "累計200時間の活動記録",
    icon: "⏰",
    category: "total_time",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalHours >= 200,
  },
  {
    id: "total_hours_500",
    name: "500時間の探求",
    description: "累計500時間の活動記録",
    icon: "⏰",
    category: "total_time",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalHours >= 500,
  },
  {
    id: "total_hours_1000",
    name: "1000時間の壁",
    description: "累計1000時間の活動記録",
    icon: "🏆",
    category: "total_time",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalHours >= 1000,
  },
  {
    id: "total_hours_2000",
    name: "2000時間の道",
    description: "累計2000時間の活動記録",
    icon: "💎",
    category: "total_time",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalHours >= 2000,
  },
  {
    id: "total_hours_5000",
    name: "5000時間の達人",
    description: "累計5000時間の活動記録",
    icon: "💎",
    category: "total_time",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.totalHours >= 5000,
  },
  {
    id: "total_hours_10000",
    name: "10000時間の伝説",
    description: "累計10000時間の活動記録",
    icon: "👑",
    category: "total_time",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.totalHours >= 10000,
  },

  // ===== 記録数系 =====
  {
    id: "records_1",
    name: "最初の一歩",
    description: "初めての記録を追加",
    icon: "📝",
    category: "records",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 1,
  },
  {
    id: "records_10",
    name: "10件記録",
    description: "10件の活動記録を追加",
    icon: "📝",
    category: "records",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 10,
  },
  {
    id: "records_50",
    name: "50件記録",
    description: "50件の活動記録を追加",
    icon: "📝",
    category: "records",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 50,
  },
  {
    id: "records_100",
    name: "100件突破",
    description: "100件の活動記録を追加",
    icon: "📊",
    category: "records",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalRecords >= 100,
  },
  {
    id: "records_200",
    name: "200件の継続者",
    description: "200件の活動記録を追加",
    icon: "📊",
    category: "records",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalRecords >= 200,
  },
  {
    id: "records_500",
    name: "500件の記録者",
    description: "500件の活動記録を追加",
    icon: "📊",
    category: "records",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalRecords >= 500,
  },
  {
    id: "records_1000",
    name: "1000件の達人",
    description: "1000件の活動記録を追加",
    icon: "🏆",
    category: "records",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalRecords >= 1000,
  },
  {
    id: "records_2000",
    name: "2000件の記録魔",
    description: "2000件の活動記録を追加",
    icon: "🏆",
    category: "records",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalRecords >= 2000,
  },
  {
    id: "records_5000",
    name: "5000件の伝説",
    description: "5000件の活動記録を追加",
    icon: "👑",
    category: "records",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.totalRecords >= 5000,
  },
  {
    id: "daily_max_8h",
    name: "フルデイ",
    description: "1日8時間以上の活動記録",
    icon: "💪",
    category: "records",
    tier: "silver",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 8,
  },
  {
    id: "daily_max_12h",
    name: "超集中",
    description: "1日12時間以上の活動記録",
    icon: "🔥",
    category: "records",
    tier: "gold",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 12,
  },

  // ===== 目標達成系 =====
  {
    id: "goal_first_daily",
    name: "初デイリー達成",
    description: "初めてデイリー目標を達成",
    icon: "🎯",
    category: "goals",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.dailyGoalsAchievedDays >= 1,
  },
  {
    id: "daily_goals_10days",
    name: "10日達成",
    description: "累計10日間デイリー目標を達成",
    icon: "🎯",
    category: "goals",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.dailyGoalsAchievedDays >= 10,
  },
  {
    id: "daily_goals_50days",
    name: "50日達成",
    description: "累計50日間デイリー目標を達成",
    icon: "🏅",
    category: "goals",
    tier: "silver",
    checkCondition: async (ctx) => ctx.dailyGoalsAchievedDays >= 50,
  },
  {
    id: "daily_goals_100days",
    name: "100日達成",
    description: "累計100日間デイリー目標を達成",
    icon: "🏆",
    category: "goals",
    tier: "gold",
    checkCondition: async (ctx) => ctx.dailyGoalsAchievedDays >= 100,
  },
  {
    id: "goal_first_period",
    name: "初期間達成",
    description: "初めて期間目標を達成",
    icon: "🎯",
    category: "goals",
    tier: "silver",
    checkCondition: async (ctx) => ctx.periodGoalsCompleted >= 1,
  },
  {
    id: "period_goals_3",
    name: "目標コレクター",
    description: "3個の期間目標を達成",
    icon: "🏅",
    category: "goals",
    tier: "silver",
    checkCondition: async (ctx) => ctx.periodGoalsCompleted >= 3,
  },
  {
    id: "period_goals_10",
    name: "目標マスター",
    description: "10個の期間目標を達成",
    icon: "🏆",
    category: "goals",
    tier: "gold",
    checkCondition: async (ctx) => ctx.periodGoalsCompleted >= 10,
  },
  {
    id: "perfect_week",
    name: "完璧な一週間",
    description: "1週間全日100%達成",
    icon: "⭐",
    category: "goals",
    tier: "gold",
    checkCondition: async (ctx) => ctx.currentStreak >= 7,
  },
  {
    id: "perfect_month",
    name: "完璧な一ヶ月",
    description: "1ヶ月100%達成",
    icon: "🌟",
    category: "goals",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.currentStreak >= 30,
  },

  // ===== WhatPulse系 =====
  {
    id: "keys_1k",
    name: "千鍵入力",
    description: "1日に1000回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 1000,
  },
  {
    id: "keys_5k",
    name: "5千鍵入力",
    description: "1日に5000回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 5000,
  },
  {
    id: "keys_10k",
    name: "1万キー",
    description: "1日に1万回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 10000,
  },
  {
    id: "keys_50k",
    name: "5万キー",
    description: "1日に5万回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "silver",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 50000,
  },
  {
    id: "keys_100k",
    name: "10万キー",
    description: "1日に10万回以上のキーストローク",
    icon: "⌨️",
    category: "whatpulse",
    tier: "gold",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 100000,
  },
  {
    id: "keys_200k",
    name: "20万キー",
    description: "1日に20万回以上のキーストローク",
    icon: "🔥",
    category: "whatpulse",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.totalKeystrokes >= 200000,
  },
  {
    id: "keys_total_500k",
    name: "累計50万キー",
    description: "累計50万回のキーストローク",
    icon: "💻",
    category: "whatpulse",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.cumulativeKeystrokes >= 500000,
  },
  {
    id: "keys_total_1m",
    name: "累計100万キー",
    description: "累計100万回のキーストローク",
    icon: "💻",
    category: "whatpulse",
    tier: "silver",
    checkCondition: async (ctx) => ctx.cumulativeKeystrokes >= 1000000,
  },
  {
    id: "keys_total_5m",
    name: "累計500万キー",
    description: "累計500万回のキーストローク",
    icon: "🖥️",
    category: "whatpulse",
    tier: "silver",
    checkCondition: async (ctx) => ctx.cumulativeKeystrokes >= 5000000,
  },
  {
    id: "keys_total_10m",
    name: "累計1000万キー",
    description: "累計1000万回のキーストローク",
    icon: "🖥️",
    category: "whatpulse",
    tier: "gold",
    checkCondition: async (ctx) => ctx.cumulativeKeystrokes >= 10000000,
  },
  {
    id: "keys_total_50m",
    name: "累計5000万キー",
    description: "累計5000万回のキーストローク",
    icon: "🤖",
    category: "whatpulse",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.cumulativeKeystrokes >= 50000000,
  },

  // ===== 特殊系 =====
  {
    id: "early_bird",
    name: "早起き鳥",
    description: "朝6時前に活動開始",
    icon: "🌅",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 1,
  },
  {
    id: "dawn_breaker",
    name: "夜明け前",
    description: "午前4〜5時台に活動開始",
    icon: "🌃",
    category: "special",
    tier: "silver",
    checkCondition: async (ctx) => ctx.hasEarlyMorningRecord,
  },
  {
    id: "night_owl",
    name: "夜型人間",
    description: "深夜0時以降に活動終了",
    icon: "🦉",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.totalRecords >= 1,
  },
  {
    id: "past_midnight",
    name: "深夜の集中",
    description: "午前2時以降まで活動を続けた",
    icon: "🌙",
    category: "special",
    tier: "silver",
    checkCondition: async (ctx) => ctx.hasLateNightRecord,
  },
  {
    id: "micro_session",
    name: "隙間の努力",
    description: "5分未満の短い記録を追加",
    icon: "⚡",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.hasShortSession,
  },
  {
    id: "multi_category_day",
    name: "マルチタスカー",
    description: "1日に3カテゴリー以上記録",
    icon: "🎨",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.categories >= 3,
  },
  {
    id: "categories_5",
    name: "バラエティスター",
    description: "5カテゴリー以上を作成",
    icon: "🌈",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.categories >= 5,
  },
  {
    id: "categories_10",
    name: "カテゴリーコレクター",
    description: "10カテゴリー以上を作成",
    icon: "🌈",
    category: "special",
    tier: "silver",
    checkCondition: async (ctx) => ctx.categories >= 10,
  },
  {
    id: "longest_session_4h",
    name: "4時間集中",
    description: "4時間以上の連続記録",
    icon: "🎯",
    category: "special",
    tier: "silver",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 4,
  },
  {
    id: "marathon_session",
    name: "マラソンセッション",
    description: "6時間以上の連続記録",
    icon: "🏃",
    category: "special",
    tier: "gold",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 6,
  },
  {
    id: "weekend_warrior",
    name: "週末戦士",
    description: "土日に8時間以上の活動",
    icon: "⚔️",
    category: "special",
    tier: "silver",
    checkCondition: async (ctx) => ctx.longestSingleSession >= 8,
  },
  {
    id: "full_day_record",
    name: "完全記録の日",
    description: "1日合計12時間以上を記録",
    icon: "📅",
    category: "special",
    tier: "gold",
    checkCondition: async (ctx) => ctx.maxDailyHours >= 12,
  },
  {
    id: "consecutive_record_30",
    name: "30日連続記録",
    description: "30日間連続で記録を追加",
    icon: "📅",
    category: "special",
    tier: "gold",
    checkCondition: async (ctx) => ctx.consecutiveDaysRecorded >= 30,
  },
  {
    id: "consecutive_record_100",
    name: "100日連続記録",
    description: "100日間連続で記録を追加",
    icon: "📅",
    category: "special",
    tier: "platinum",
    checkCondition: async (ctx) => ctx.consecutiveDaysRecorded >= 100,
  },
  {
    id: "comeback_king",
    name: "カムバック",
    description: "ストリークが途切れた後に再び連続記録を開始",
    icon: "💪",
    category: "special",
    tier: "bronze",
    checkCondition: async (ctx) => ctx.longestStreak > ctx.currentStreak && ctx.currentStreak >= 1,
  },
  {
    id: "anniversary",
    name: "記念日",
    description: "365日以上継続して記録を積み重ねた",
    icon: "🎂",
    category: "special",
    tier: "gold",
    checkCondition: async (ctx) => ctx.consecutiveDaysRecorded >= 365,
  },
];
